# Generated by Django 4.2.6 on 2024-07-10 20:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_fist_name_user_first_name'),
        ('core', '0003_alter_policy_dept_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docAuthor', to='user.authuser')),
                ('docCat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCategory', to='core.category')),
                ('docDept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docDepartment', to='core.department')),
            ],
        ),
    ]
